// ------------- FILE HEADER -------------
// Author ✅: 
// Assignment ✅:
// Date ✅:
// Citations: 


// ------------- CODE -------------
// Include standard input/output support: https://en.cppreference.com/w/cpp/header/iostream
#include <iostream>
// cout
// https://en.cppreference.com/cpp/io/basic_ostream

// cin
// https://en.cppreference.com/cpp/io/basic_istream

// Use the standard namespace: https://en.cppreference.com/w/cpp/language/namespace
using namespace std;

// Function prototypes (if any)


// Main function
// https://en.cppreference.com/w/cpp/language/main_function.html
int main() {
  // C++ generated interactively with copilot from my design
  // Reference links generated with prompt:
  // Add comment links to cppreference.com  first occurence of each c++ element 


  // Write output to the console: https://en.cppreference.com/w/cpp/io/basic_ostream/operator_ltlt
  cout << "Welcome to my Weekly Payroll program!!" << endl;

  cout << "Enter your employee ID number (numbers only): ";
  // Declare an integer variable: https://en.cppreference.com/w/cpp/language/types
  int employeeID = 0;
  // Read input from the console: https://en.cppreference.com/w/cpp/io/basic_istream/operator_gtgt
  cin >> employeeID;

  cout << "Enter number of hours worked (whole numbers): ";
  int employeeHours = 0;
  cin >> employeeHours;

  cout << "Enter the hourly rate: ";
  int USDPerHour = 0;
  cin >> USDPerHour;

  cout << "Enter the federal withholding rate: ";
  int integerWithholdingRate = 0;
  cin >> integerWithholdingRate;

  // Calculations
  // Declare floating-point variables: https://en.cppreference.com/w/cpp/language/types
  double grossPayUSD = employeeHours * USDPerHour;
  double decimalWithholdingRate = integerWithholdingRate / 100.0;
  double federalTaxWithholdingUSD = grossPayUSD * decimalWithholdingRate;
  double netPayUSD = grossPayUSD - federalTaxWithholdingUSD;

  // Output
  cout << "Your Payroll Summary: " << endl;
  cout << "Total Gross Pay: $" << grossPayUSD << endl;
  cout << "Federal Tax Withholding: $" << federalTaxWithholdingUSD << endl;
  cout << "Net Pay: $" << netPayUSD << endl;
  cout << "Thank you for using my Weekly Payroll program!!" << endl;

  // Return from main: https://en.cppreference.com/w/cpp/language/return
  return 0;
}

// Function implementations (if any)


// ------------- DESIGN -------------
/* 
Program Name:
Tax Calculator

Program Description:
During September, businesses across the United States take time to thank their payroll teams and reflect on all of the successful paydays of the past year. While technology has made it easier than ever for HR teams to pay their employees, crunching the numbers can still be a laborious task for payroll professionals. National Payroll Week serves as a reminder that there are dedicated professionals working hard everyday to ensure we get paid accurately and on time.

Design:
A. INPUT
int employeeID = 0;
int employeeHours = 0;
int USDPerHour = 0;
int integerWithholdingRate = 0;

B. OUTPUT
double grossPayUSD = 0.0;
double federalTaxWitholdingUSD = 0.0;
double netPayUSD = 0.0;

C. CALCULATIONS
First calculate the total gross pay from the hours worked and the hourly rate inputs. 
grossPayUSD = employeeHours * USDPerHour;
double decimalWitholdingRate = integerWithholdingRate / 100.0;
federalTaxWitholdingUSD = grossPayUSD * decimalWitholdingRate;
netPayUSD = grossPayUSD - federalTaxWitholdingUSD;

D. LOGIC and ALGORITHMS
WELCOME "Welcome to my Weekly Payroll program!!"

PROMPT "Enter your employee ID number (numbers only): "
INPUT employeeID

PROMPT "Enter number of hours worked (whole numbers): "
INPUT employeeHours

PROMPT "Enter the hourly rate: "
INPUT USDPerHour

PROMPT "Enter the federal withholding rate: "
INPUT federalWithholdingRatePercent

DO CALCULATIONS

HEADING "Your Payroll Summary: "

LABEL "Gross Pay: "
DATA grossPayUSD

LABEL "Federal Tax Withholding: "
DATA federalTaxWitholdingUSD

LABEL "Net Pay: "
DATA netPayUSD

GOODBYE "Thank you for using my Weekly Payroll program!!"

FLOWCHART in drawio format generated by copilot from section D
https://drive.google.com/file/d/1UfENDKp20GqECEw0Zlkh6XJNesFNSEau/view?usp=sharing


SAMPLE RUNS
Welcome to my Weekly Payroll program!!
Enter your employee ID number (numbers only): 34567
Enter number of hours worked (whole numbers): 40
Enter the hourly rate: 17
Enter the federal withholding rate: 15
Your Payroll Summary:
Total Gross Pay: $680
Federal Tax Withholding: $102
Net Pay: $578
Thank you for using my Weekly Payroll program!!


Welcome to my Weekly Payroll program!!
Enter your employee ID number (numbers only): 12345
Enter number of hours worked (whole numbers): 30
Enter the hourly rate: 22
Enter the federal withholding rate: 10
Your Payroll Summary:
Total Gross Pay: $660
Federal Tax Withholding: $66
Net Pay: $594
Thank you for using my Weekly Payroll program!!


*/
